services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: hangman
      MYSQL_ROOT_PASSWORD: lazar123

  hangman:
    image: lazardukov/hangman-game:v2
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: lazar123
      MYSQL_DATABASE: hangman